### PR TITLE
Session by Maxim Salnikov added + some formatting fixed

### PR DESCRIPTION
**Pull request by webmaxru**
I added my new session on WebNN. More details:
🔗 Key resources:

✅ Source code: [https://github.com/webmaxru/ng-ai](https://github.com/webmaxru/ng-ai)
✅ Demo: [https://icy-bush-0912f3610.5.azurestaticapps.net](https://icy-bush-0912f3610.5.azurestaticapps.net/) (WIP)
✅ Slides: [https://slideshare.net/slideshow/privacy-first-in-browser-generative-ai-web-apps-offline-ready-future-proof-standards-based/273142915](https://slideshare.net/slideshow/privacy-first-in-browser-generative-ai-web-apps-offline-ready-future-proof-standards-based/273142915)
✅ Details: [https://sessionize.com/s/maxim-salnikov/privacy-first-in-browser-generative-ai-web-apps-of/105248](https://sessionize.com/s/maxim-salnikov/privacy-first-in-browser-generative-ai-web-apps-of/105248)

### CODE REVIEW

**Review by anssiko — APPROVED** [review]
Thank you for this contribution.

You could consider adding your demo app https://ng-ai-zeta.vercel.app/ to the Demos section.

**Comment by ibelem** [comment]
Ah, I didn't see this PR when submitting https://github.com/webmachinelearning/awesome-webnn/pull/11 which added both @webmaxru 's  presentation and demos.

Great presentation and demos @webmaxru !  ⭐⭐⭐ Thank you! 

@anssiko Please wait for @webmaxru's update, then I will rebase https://github.com/webmachinelearning/awesome-webnn/pull/11 based on merged https://github.com/webmachinelearning/awesome-webnn/pull/10. Thanks! :)

**Comment by webmaxru** [comment]
@anssiko: I've added link to my demo. Thanks for this suggestion!

I plan to scale up my community visibility and influence on WebNN topic. Please, keep me in mind if you have any requests from the tech communities, conferences, companies on landing WebNN inspirational/technical sessions - my pleasure to deliver these!

**Comment by anssiko** [comment]
@webmaxru keep up the great work! Demos and open-source projects encourage experimentation and drive further innovation. Feedback from these efforts is crucially important input to inform the future direction of the WebNN API. You're invited to share feedback from early adopters. It is the most convenient through our [GitHub repo](https://github.com/webmachinelearning/webnn). You're also invited to [join](https://webmachinelearning.github.io/community/#join) the effort. Our [triage guidance](https://github.com/webmachinelearning/webnn/blob/main/docs/IssueTriage.md) documents our current focus areas for the spec development.

**Pull request merged**
